[build]
  publish = "public"
  command = "npm run build"

# Redirect default Netlify subdomain to primary domain
# [[redirects]]
#   from = "https://leptest-niko-test.netlify.com/*"
#   to = "http://nikotrack.com/:splat"
#   status = 301
#   force = true
