[build]
  publish = "public"
  command = "npm run build"

# Redirect default Netlify subdomain to primary domain
[[redirects]]
  from = "http://leptest-niko-test.netlify.com/*"
  to = "http://staging.nikotrack.com/:splat"
  status = 301
