backend:
  name: git-gateway
  branch: master
media_folder: static/img
public_folder: /img
collections:
  -
    name: products
    label: Products
    folder: src/pages/products
    create: true
    slug: '{{slug}}'
    editor:
      preview: true
    fields:
      -
        label: 'Template Key'
        name: templateKey
        widget: hidden
        default: product-landing
      -
        label: Title
        name: title
        widget: string
      -
        label: Sections
        name: customSections
        widget: list
        fields:
          -
            label: Title
            name: title
            widget: string
          -
            label: Body
            name: body
            widget: markdown
          -
            label: Images
            name: images
            widget: list
            fields:
              -
                label: Image
                name: imageUrl
                widget: image
              -
                label: 'Alt description'
                name: imageAlt
                widget: string
          -
            label: PDFs
            name: pdfs
            widget: list
            fields:
              -
                label: Title
                name: title
                widget: string
              -
                label: File
                name: pdfUrl
                widget: file
              -
                label: Thumbnail
                name: pdfThumb
                widget: image
          -
            label: Videos
            name: videos
            widget: list
            fields:
              -
                label: 'YouTube ID'
                name: youTubeId
                widget: string
              -
                label: 'Description'
                name: vidDescription
                widget: string
          -
            label: Products
            name: products
            widget: list
            fields:
              -
                label: Title
                name: title
                widget: string
              -
                label: Image
                name: imageUrl
                widget: image
  -
    name: blog
    label: Blog
    folder: src/pages/blog
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      -
        label: 'Template Key'
        name: templateKey
        widget: hidden
        default: blog-post
      -
        label: Title
        name: title
        widget: string
      -
        label: 'Publish Date'
        name: date
        widget: datetime
      -
        label: Description
        name: description
        widget: text
      -
        label: Body
        name: body
        widget: markdown
  -
    name: pages
    label: Pages
    files:
      -
        file: src/pages/about/index.md
        label: About
        name: about
        fields:
          -
            label: 'Template Key'
            name: templateKey
            widget: hidden
            default: about-page
          -
            label: Title
            name: title
            widget: string
          -
            label: Body
            name: body
            widget: markdown
      -
        file: src/pages/services/index.md
        label: Services
        name: services
        fields:
          -
            label: 'Template Key'
            name: templateKey
            widget: hidden
            default: service-page
          -
            label: Title
            name: title
            widget: string
          -
            label: Image
            name: image
            widget: image
          -
            label: Heading
            name: heading
            widget: string
          -
            label: Description
            name: description
            widget: markdown
          -
            label: Services
            name: services
            widget: list
            fields:
              -
                label: Title
                name: title
                widget: string
              -
                label: Image
                name: imageUrl
                widget: image
              -
                label: ImageAlt
                name: imageAlt
                widget: string
              -
                label: Description
                name: description
                widget: string
