backend:
  name: git-gateway
  branch: master
media_folder: static/img
public_folder: /img
collections:
  -
    name: products
    label: Products
    folder: src/pages/products
    create: true
    slug: '{{slug}}'
    editor:
      preview: true
    fields:
      -
        label: 'Template Key'
        name: templateKey
        widget: hidden
        default: product-landing
      -
        label: Order
        name: order
        widget: string
      -
        label: Nav title
        name: navTitle
        widget: string
      -
        label: Hero Image
        name: heroImage
        widget: image
      -
        label: Hero Body
        name: heroDescription
        widget: markdown
      -
        label: Title
        name: title
        widget: string
      -
        label: Sections
        name: customSections
        widget: list
        fields:
          -
            label: Title
            name: title
            widget: string
          -
            label: Nav Title
            name: navTitle
            widget: string
          -
            label: Body
            name: body
            widget: markdown
          -
            label: Images
            name: images
            widget: list
            fields:
              -
                label: Image
                name: imageUrl
                widget: image
              -
                label: 'Alt description'
                name: imageAlt
                widget: string
          -
            label: PDFs
            name: pdfs
            widget: list
            fields:
              -
                label: Title
                name: title
                widget: string
              -
                label: File
                name: pdfUrl
                widget: file
              -
                label: Thumbnail
                name: pdfThumb
                widget: image
          -
            label: Videos
            name: videos
            widget: list
            fields:
              -
                label: 'YouTube ID'
                name: youTubeId
                widget: string
              -
                label: 'Description'
                name: vidDescription
                widget: string
          -
            label: Flipbooks
            name: flipbooks
            widget: list
            fields:
              -
                label: Issuu ID
                name: issueId
                widget: string
  -
    name: blog
    label: Latest News
    folder: src/pages/blog
    create: true
    slug: '{{year}}-{{month}}-{{day}}-{{slug}}'
    fields:
      -
        label: 'Template Key'
        name: templateKey
        widget: hidden
        default: blog-post
      -
        label: Title
        name: title
        widget: string
      -
        label: 'Publish Date'
        name: date
        widget: datetime
      -
        label: Description
        name: description
        widget: text
      -
        label: Body
        name: body
        widget: markdown
  -
    name: pages
    label: Pages
    files:
      -
        file: src/pages/contact.md
        label: Contact
        name: contact
        fields:
          -
            label: 'Template Key'
            name: templateKey
            widget: hidden
            default: contact
          -
            label: Title
            name: title
            widget: string
